cabs/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name='cabs'


urlpatterns=[
    url(r'^$',views.index,name='main'),
    url(r'^post/$', views.post_view, name='post'),
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^bookings/$', views.booking_view, name='bookings'),
    path('bookings/<int:id>/cancel', views.cancel_view, name='cancel'),
    url(r'^notifications/$', views.notification_view, name='notifications'),
    url(r'^aboutus/$', views.aboutus_view, name='aboutus'),
    url(r'^feedback/$', views.feedback_view, name='feedback'),
    url(r'^contact/$', views.contact_view, name='contact'),
    path('brequest/<name1>/<name2>/<int:id>', views.request_view, name='brequest'),
    url(r'^requestpage/$', views.requestpage_view, name='requestpage'),
    path('requestpage/<int:id>/Rcancel', views.Rcancel_view, name='Rcancel'),
    path('Fgroup2/<int:bid>/<name1>/<name2>/<int:rid>', views.Fgroup2_view, name='Fgroup2'),
    url(r'^groups/$', views.groups_view, name='groups'),
    path('groups/<int:id>/Gcancel', views.Gcancel_view, name='Gcancel'),
    path('Grequest2/<requester>/<name1>/<name2>/<int:id>', views.Grequest2_view, name='Grequest2'),
    path('Fgroup3/<int:bid>/<name1>/<name2>/<name3>/<int:rid>', views.Fgroup3_view, name='Fgroup3'),
    path('groups/<int:id>/Gcancel3', views.Gcancel3_view, name='Gcancel3'),
    path('Grequest3/<requester>/<name1>/<name2>/<name3>/<int:id>', views.Grequest3_view, name='Grequest3'),
    path('Fgroup4/<int:bid>/<name1>/<name2>/<name3>/<name4>/<int:rid>', views.Fgroup4_view, name='Fgroup4'),
    path('groups/<int:id>/Gcancel4', views.Gcancel4_view, name='Gcancel4'),
    path('requestpage/<int:id>/Rcancel2', views.Rcancel2_view, name='Rcancel2'),
    path('requestpage/<int:id>/Rcancel3', views.Rcancel3_view, name='Rcancel3'),
]

urlpatterns+=staticfiles_urlpatterns()

cabsharing/urls.py
from django.contrib import admin
from django.urls import path,include
from django_private_chat import urls as django_private_chat_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cabs/', include('cabs.urls')),
    path('', include('django_private_chat.urls')),
]

templates/aboutus.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Cabbie</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous">
    <link rel='shortcut icon' type='image/x-icon' href='https://img.icons8.com/bubbles/2x/car.png' />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aboutusstyle.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light py-3">
    <div class="container"><a href="{% url 'cabs:main' %}" class="navbar-brand d-flex align-items-center"> <i
            class="fa fa-car" aria-hidden="true"></i></i><strong>Cabbie</strong></a>
        <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"><span class="navbar-toggler-icon"></span></button>
        <div id="navbarSupportedContent" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'cabs:main' %}" class="nav-link font-italic"> Home </a></li>
                <li class="nav-item active"><a href="{% url 'cabs:feedback' %}" class="nav-link font-italic">
                    Feedback </a></li>
                <li class="nav-item active"><a href="{% url 'cabs:contact' %}" class="nav-link font-italic">Contact
                    us </a></li>

            </ul>
        </div>
    </div>
</nav>

<div class="bg-light">
    <div class="container py-5">
        <div class="row h-100 align-items-center py-5">
            <div class="col-lg-6">
                <h1 class="display-4">About cabbie</h1>
                <p class="lead text-muted mb-0">Make the most with carpool.</p>

                {% block content %}
                {% endblock %}
            </div>

            <div class="col-lg-6 d-none d-lg-block"><img
                    src="https://res.cloudinary.com/mhmd/image/upload/v1556834136/illus_kftyh4.png" alt=""
                    class="img-fluid"></div>
        </div>
    </div>
</div>

<div class="bg-white py-5">
    <div class="container py-5">
        <div class="row align-items-center mb-5">
            <div class="col-lg-6 order-2 order-lg-1"><i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>
                <h2 class="font-weight-light">For Carpool Givers</h2>
                <p class="font-italic text-muted mb-4">Share your car empty seats and cut down your commuting cost.
                    Enjoy meeting amazing new people everyday.</p>
            </div>
            <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img
                    src="https://res.cloudinary.com/mhmd/image/upload/v1556834139/img-1_e25nvh.jpg" alt=""
                    class="img-fluid mb-4 mb-lg-0"></div>
        </div>
        <div class="row align-items-center">
            <div class="col-lg-5 px-5 mx-auto"><img
                    src="https://res.cloudinary.com/mhmd/image/upload/v1556834136/img-2_vdgqgn.jpg" alt=""
                    class="img-fluid mb-4 mb-lg-0"></div>
            <div class="col-lg-6"><i class="fa fa-leaf fa-2x mb-3 text-primary"></i>
                <h2 class="font-weight-light">For Carpool Takers</h2>
                <p class="font-italic text-muted mb-4">Ride with like minded people and Save 70% on
                    your taxi fares that reduce your transportation expense significantly</p>
            </div>
        </div>
    </div>
</div>
<div class="bg-light py-5">
    <div class="container py-5">
        <div class="row mb-4">
            <div class="col-lg-5">
                <h2 class="display-4 font-weight-light">About me</h2>
                <p class="font-italic text-muted">This website is created and designed by Akshat Rana.</p>
            </div>
        </div>

        <div class="row text-center">
            <!-- Team item-->
            <div class="col-xl-3 col-sm-6 mb-5">
                <div class="bg-white rounded shadow-sm py-5 px-4"><img src="{% static 'avatar.jpg' %}" alt=""
                                                                       width="100"
                                                                       class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
                    <h5 class="mb-0">Akshat Rana</h5><span class="small text-uppercase text-muted">Founder</span>
                    <ul class="social mb-0 list-inline mt-3">
                        <li class="list-inline-item"><a href="https://www.facebook.com/akshat.rana.33"
                                                        class="social-link"><i class="fa fa-facebook-f"></i></a></li>
                        <li class="list-inline-item"><a href="https://www.instagram.com/akshat7010/"
                                                        class="social-link"><i class="fa fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a href="https://in.linkedin.com/in/akshat-rana-343568188"
                                                        class="social-link"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
            <!-- End-->


        </div>
    </div>
</div>

<footer class="bg-light pb-5">
    <div class="container text-center">
        <p class="font-italic text-muted mb-0">&copy; Copyrights Cabbie.com All rights reserved.</p>
    </div>
</footer>

</body>
</html>

templates/base.html
<!DOCTYPE HTML>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href="{% static 'css/bootstrap.css' %}" media="all" rel="stylesheet" type="text/css">
        <link href="{% static 'css/style.css' %}" media="all" rel="stylesheet" type="text/css">
        <title>Cabbie</title>
        <link href='https://img.icons8.com/bubbles/2x/car.png' rel='shortcut icon' type='image/x-icon' />
        {% block css %}{% endblock %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous">
    </head>

    <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3">
    <div class="container"><a class="navbar-brand d-flex align-items-center" href="{% url 'cabs:main' %}"> <i
            aria-hidden="true" class="fa fa-car"></i></i><strong>Cabbie</strong></a>
    </div>
    </nav>
        {% block content %}{% endblock %}

        <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/bootstrap.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'js/handlebars-v1.3.0.js' %}" type="text/javascript"></script>
        {% block extra_js %}{% endblock %}
    </body>

</html>

templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Cabbie</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css"
          crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          crossorigin="anonymous">
    <link rel='shortcut icon' type='image/x-icon' href='https://img.icons8.com/bubbles/2x/car.png' />
    <link rel="stylesheet" type="text/css" href="{% static 'css/aboutusstyle.css' %}">
    <link href="{% static 'css/poststyle.css' %}" rel="stylesheet">
    <link href="{% static 'css/requeststyle.css' %}" rel="stylesheet">
</head>
<body class="bg-light py-5">

<nav class="navbar navbar-expand-lg navbar-light bg-light py-3">
    <div class="container"><a href="{% url 'cabs:main' %}" class="navbar-brand d-flex align-items-center"> <i
            class="fa fa-car" aria-hidden="true"></i></i><strong>Cabbie</strong></a>
        <button type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"><span class="navbar-toggler-icon"></span></button>
        <div id="navbarSupportedContent" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'cabs:main' %}" class="nav-link font-italic"> Home </a></li>
                <li class="nav-item active"><a href="{% url 'cabs:post' %}" class="nav-link font-italic"> Book </a></li>
                <li class="nav-item active"><a href="{% url 'cabs:feedback' %}" class="nav-link font-italic">
                    Feedback </a></li>
                <li class="nav-item active"><a href="{% url 'cabs:contact' %}" class="nav-link font-italic">Contact
                    us </a></li>
                {% if user.is_authenticated %}
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Welcome {{user.username}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'cabs:bookings' %}">My bookings</a>
            <a class="dropdown-item" href="/dialogs/akshat7010">My chats</a>
          <a class="dropdown-item" href="{% url 'cabs:notifications' %}">Notifications
            <strong class="fa-stack-xs" style="color:red">&nbsp; {{nnum}}</strong>
          </a>
            <a class="dropdown-item" href="{% url 'cabs:requestpage' %}">Requests
            <strong class="fa-stack-xs" style="color:red">&nbsp;{{num}}</strong>
            </a>
            <a class="dropdown-item" href="{% url 'cabs:groups' %}">My Groups</a>
          <div class="dropdown-divider"></div>
          <form class="form-inline my-2 my-lg-0" action="/cabs/logout/" method="post" >
						{% csrf_token %}
    					<button type="submit" style="background:none;cursor: pointer;
							border: 0; color:#333 ;float:right;">&nbsp;&nbsp;&nbsp;&nbsp;Logout</button>
          </form>
        </div>
      </li>
        {% endif %}
      {% if not user.is_authenticated %}
		<li class="nav-item active"><a href="{% url 'cabs:login' %}" class="nav-link font-italic"> Login </a></li>
        <li class="nav-item active"><a href="{% url 'cabs:signup' %}" class="nav-link font-italic"> Signup </a></li>
      	{% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %} {% endblock %}
<footer class="bg-light pb-5">
    <div class="container text-center">
        <p class="font-italic text-muted mb-0">&copy; Copyrights Cabbie.com All rights reserved.</p>
    </div>
</footer>
</body>
</html>

templates/bookings.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
<div class="bg-light py-5">
    <div class="container py-5">
        <h2>{{ title }} :</h2>
        <br>
        {% if not booking_list %}
        <h3>Sorry, no results found.</h3>
        {% else %}
        {% for obj in booking_list %}
        <div class="card">
          <h5 class="card-header">{{ obj.date}}  {{ obj.time}}</h5>
          <div class="card-body">
            <p class="card-text">Number of passengers: {{ obj.passengers}}</p>
              <p class="card-text">Gender: {{ obj.gender}}</p>
              <p class="card-text">Pickup from: {{ obj.pickup_from}}</p>
              <p class="card-text">Destination: {{ obj.destination}}</p>
             <p class="card-text">Booking ID: {{ obj.id}}</p>
            <a class="btn btn-primary" href="{{obj.id}}/cancel" onclick="myFunction();">Cancel your booking</a>
              <script>
                                function myFunction() {
                                  alert("Your booking has been cancelled.");
                                }
              </script>
          </div>
        </div>
        <br>
{% endfor %}
{% endif %}
    </div>
</div>
{% endblock %}

templates/contact.html
{% extends 'home.html' %}

{% block newcontent %}

<p></p>
<p></p>
<h2 class="display-4 font-weight-light">Contact us</h2>
<p class="font-italic text-muted"><i class="fa fa-phone" aria-hidden="true"></i> Phone : 8826635195</p>
<p class="font-italic text-muted"><i class="fa fa-envelope" aria-hidden="true"></i> E-mail : akshat7010@gmail.com</p>

{% endblock %}

templates/home.html
{% extends 'base1.html' %}
{% load static %}
{% block content %}
<div class="bg-light">
    <div class="container py-5">
        <div class="row h-100 align-items-center py-5">
            <div class="col-lg-6">
                <h1 class="display-4">Cabbie</h1>
                <p class="lead text-muted mb-0">Make the most with carpool.</p>
                {% block newcontent %}
                {% endblock %}
            </div>
            <div class="col-lg-6 d-none d-lg-block"><img
                    src="https://res.cloudinary.com/mhmd/image/upload/v1556834136/illus_kftyh4.png" alt=""
                    class="img-fluid"></div>
        </div>
    </div>
</div>

<div class="bg-white py-5">
    <div class="container py-5">
        <div class="row align-items-center mb-5">
            <div class="col-lg-6 order-2 order-lg-1"><i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>
                <h2 class="font-weight-light">For Carpool Givers</h2>
                <p class="font-italic text-muted mb-4">Share your car empty seats and cut down your commuting cost.
                    Enjoy meeting amazing new people everyday.</p>
            </div>
            <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img
                    src="https://res.cloudinary.com/mhmd/image/upload/v1556834139/img-1_e25nvh.jpg" alt=""
                    class="img-fluid mb-4 mb-lg-0"></div>
        </div>
        <div class="row align-items-center">
            <div class="col-lg-5 px-5 mx-auto"><img
                    src="https://res.cloudinary.com/mhmd/image/upload/v1556834136/img-2_vdgqgn.jpg" alt=""
                    class="img-fluid mb-4 mb-lg-0"></div>
            <div class="col-lg-6"><i class="fa fa-leaf fa-2x mb-3 text-primary"></i>
                <h2 class="font-weight-light">For Carpool Takers</h2>
                <p class="font-italic text-muted mb-4">Ride with like minded people and Save 70% on
                    your taxi fares that reduce your transportation expense significantly</p>
            </div>
        </div>
    </div>
</div>
<div class="bg-light py-5">
    <div class="container py-5">
        <div class="row mb-4">
            <div class="col-lg-5">
                <h2 class="display-4 font-weight-light">About me</h2>
                <p class="font-italic text-muted">This website is created and designed by Akshat Rana.</p>
            </div>
        </div>

        <div class="row text-center">
            <!-- Team item-->
            <div class="col-xl-3 col-sm-6 mb-5">
                <div class="bg-white rounded shadow-sm py-5 px-4"><img src="{% static 'avatar.jpg' %}" alt=""
                                                                       width="100"
                                                                       class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
                    <h5 class="mb-0">Akshat Rana</h5><span class="small text-uppercase text-muted">Founder</span>
                    <ul class="social mb-0 list-inline mt-3">
                        <li class="list-inline-item"><a href="https://www.facebook.com/akshat.rana.33"
                                                        class="social-link"><i class="fa fa-facebook-f"></i></a></li>
                        <li class="list-inline-item"><a href="https://www.instagram.com/akshat7010/"
                                                        class="social-link"><i class="fa fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a href="https://in.linkedin.com/in/akshat-rana-343568188"
                                                        class="social-link"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>
            <!-- End-->


        </div>
    </div>
</div>

{% endblock %}

templates/index.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Cabbie</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <link rel='shortcut icon' type='image/x-icon' href="https://img.icons8.com/bubbles/2x/car.png">
    <link href="{% static 'css/style1.css' %}" rel="stylesheet">

</head>
<body class="text-center">
    <form method="post" class="form-signin" style="max-width: 330px;">
        <a href="{% url 'cabs:main' %}">
            <img class="mb-4" src="https://img.icons8.com/bubbles/2x/car.png" alt="" width="72" height="72"></a>
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <p></p>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2020-2021</p>
    </form>
</body>
</html>

templates/post.html
{% extends 'base1.html' %}

{% block content %}
<div class="body-class">
    <div class="text-center">
        <h1>Post your cab timings</h1>
        <h2>Share the information below</h2>
        <form action="{% url 'cabs:post' %}" method="post" enctype="multipart/form-data" class="form-signin">
            {% csrf_token %}
            {{ form }}
            <p>Please enter date in the format (yyyy-mm-dd)</p>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Book</button>
        </form>
    </div>
</div>
{% endblock %}

templates/signup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Cabbie</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <link rel='shortcut icon' type='image/x-icon' href="https://img.icons8.com/bubbles/2x/car.png">
    <link href="{% static 'css/style1.css' %}" rel="stylesheet">

</head>
<body class="text-center">
<form method="post" class="form-signin">
    <a href="{% url 'cabs:main' %}">
    <img class="mb-4" src="https://img.icons8.com/bubbles/2x/car.png" alt="" width="72" height="72">
    </a>
    <h1 class="h3 mb-3 font-weight-normal">Sign up</h1>
    {% csrf_token %}
    {{ form.as_p }}
    <p></p>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Signup</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2020-2021</p>
</form>
</body>
</html>

templates/thankyou.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Cabbie</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	<link rel='shortcut icon' type='image/x-icon' href='https://img.icons8.com/bubbles/2x/car.png' />
  <link href="{% static 'css/poststyle.css' %}" rel="stylesheet">
</head>
<body class="jumbotron text-center">
  <h1 class="display-3">Thank You!</h1>
  <p class="lead"><strong>We have received your feedback.</strong> Hope to see you soon!</p>
  <hr>
  <p>
    Having trouble? <a href="{% url 'cabs:contact' %}">Contact us</a>
  </p>
  <p class="lead">
    <a class="btn btn-primary btn-sm" href="{% url 'cabs:main' %}" role="button">Continue to homepage</a>
  </p>
</body>
</html>